# Generated by Django 2.1.7 on 2019-03-04 02:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='blog',
            new_name='bloglist',
        ),
        migrations.AlterModelTable(
            name='bloglist',
            table='bloglist',
        ),
    ]
