# Generated by Django 2.1.7 on 2019-03-04 09:20

from django.db import migrations
import mdeditor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20190304_0250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloglist',
            name='content',
            field=mdeditor.fields.MDTextField(),
        ),
    ]
