# Generated by Django 2.1.7 on 2019-03-05 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_bloglist_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloglist',
            name='total_views',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
