# Generated by Django 2.1.7 on 2019-03-08 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lovers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='songer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('songername', models.CharField(max_length=100)),
                ('songid', models.IntegerField(default=1024)),
            ],
        ),
        migrations.AlterField(
            model_name='loveclass',
            name='lovecate',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AddField(
            model_name='songer',
            name='musicname',
            field=models.ForeignKey(default='null', on_delete='null', to='lovers.loveclass', to_field='lovecate'),
        ),
    ]
