# Generated by Django 2.1.7 on 2019-03-08 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lovers', '0002_auto_20190308_1112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='songer',
            name='musicname',
            field=models.CharField(max_length=100),
        ),
    ]
