# Generated by Django 2.1.7 on 2019-03-11 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lovers', '0003_auto_20190308_1125'),
    ]

    operations = [
        migrations.CreateModel(
            name='songcomment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('songname', models.CharField(max_length=100)),
                ('commenter', models.CharField(max_length=100)),
                ('comment', models.TextField()),
                ('likedcount', models.IntegerField(default=0)),
                ('avatarurl', models.CharField(max_length=512)),
                ('comment_time', models.DateTimeField()),
            ],
        ),
    ]
