# Generated by Django 2.1.7 on 2019-03-12 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lovers', '0004_songcomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='songcomment',
            name='comment_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
