# Generated by Django 2.1.7 on 2019-03-01 07:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='commonDity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commonName', models.CharField(max_length=100)),
                ('platform', models.CharField(max_length=100)),
                ('commonNum', models.IntegerField(default=0)),
                ('update_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '商品信息',
                'db_table': 'commondity',
                'ordering': ['-update_time'],
            },
        ),
    ]
