# Generated by Django 2.1.7 on 2019-03-01 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commodity', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commondity',
            options={'ordering': ['-commonNum'], 'verbose_name': '商品信息'},
        ),
    ]
