# Generated by Django 2.1.7 on 2019-03-01 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commodity', '0002_auto_20190301_0818'),
    ]

    operations = [
        migrations.CreateModel(
            name='shopname',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('common_id', models.IntegerField()),
                ('commonNum', models.IntegerField()),
                ('platform', models.CharField(max_length=100)),
                ('image', models.CharField(max_length=100)),
                ('shopurl', models.CharField(max_length=100)),
                ('price', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': '店家信息',
                'db_table': 'shopname',
                'ordering': ['-commonNum'],
            },
        ),
    ]
