# Generated by Django 2.1.7 on 2019-03-01 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commodity', '0003_shopname'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopname',
            name='commonName',
            field=models.CharField(default='null', max_length=100),
        ),
    ]
