# Generated by Django 2.1.7 on 2019-03-15 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commodity', '0005_shopname_shopname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shopname',
            name='shopname',
        ),
        migrations.AddField(
            model_name='shopname',
            name='shop_name',
            field=models.CharField(default='null', max_length=100),
        ),
    ]
